export const CHAT_PANEL_TAB_HEADER_HEIGHT_PX = 44;
export const CHAT_PANEL_PUBLISHED_HEADER_HEIGHT_PX = 40;
export const CHAT_PANEL_HEADER_STACK_HEIGHT_PX =
  CHAT_PANEL_TAB_HEADER_HEIGHT_PX + CHAT_PANEL_PUBLISHED_HEADER_HEIGHT_PX;
export const CHAT_PANEL_TRANSCRIPT_TOP_GAP_PX = 24;
export const CHAT_PANEL_TRANSCRIPT_TOP_PADDING_PX =
  CHAT_PANEL_HEADER_STACK_HEIGHT_PX + CHAT_PANEL_TRANSCRIPT_TOP_GAP_PX;
